version: "3.9"
services:
  server:
    build: ./python
    ports:
      - "5000:5000"
    volumes:
      - ./python:/main
    environment:
      FLASK_ENV: development
  web:
    build: ./ui/encryption
    ports:
      - "3000:3000"
    volumes:
      - ./ui/encryption:/user/src/app
    depends_on:
      - server
